import {
  Bell,
  BriefcaseBusiness,
  Building2,
  ClipboardList,
  Factory,
  FileText,
  Lightbulb,
  Megaphone,
  NotebookPen,
  Package,
  ShieldCheck,
  Truck,
  Users,
} from "lucide-react";
import type {
  Attachment,
  Board,
  FeedItem,
  Notification,
  Participant,
  ThreadComment,
} from "./types";

export const boards: Board[] = [
  {
    id: "all",
    name: "전체 피드",
    kind: "company",
    unread: 8,
    pinned: true,
    description: "공지, 이슈, 빠른 커뮤니케이션",
    icon: Megaphone,
  },
  {
    id: "contents",
    name: "콘텐츠팀",
    kind: "team",
    unread: 2,
    description: "기획, 제작, 상세페이지 업무",
    icon: FileText,
  },
  {
    id: "sales",
    name: "영업팀",
    kind: "team",
    unread: 4,
    description: "거래처, 견적, 매출 이슈",
    icon: BriefcaseBusiness,
  },
  {
    id: "production",
    name: "생산팀",
    kind: "team",
    unread: 3,
    description: "생산 일정과 재고 확인",
    icon: Factory,
  },
  {
    id: "logistics",
    name: "물류팀",
    kind: "team",
    unread: 7,
    description: "입출고, 배송, 지연 관리",
    icon: Truck,
  },
  {
    id: "new-business",
    name: "신사업팀",
    kind: "team",
    unread: 1,
    description: "신규 프로젝트와 시장 조사",
    icon: Lightbulb,
  },
  {
    id: "management",
    name: "경영관리실",
    kind: "team",
    unread: 0,
    description: "정산, 인사, 비용 관리",
    icon: Building2,
  },
  {
    id: "ceo",
    name: "대표이사",
    kind: "team",
    unread: 0,
    description: "전사 현황과 의사결정",
    icon: ShieldCheck,
  },
  {
    id: "weekly",
    name: "업무 게시판",
    kind: "worklog",
    unread: 6,
    pinned: true,
    description: "주간 단위 업무 히스토리",
    icon: ClipboardList,
  },
  {
    id: "memo",
    name: "개인 메모장",
    kind: "memo",
    unread: 0,
    description: "개인 기록과 임시 저장",
    icon: NotebookPen,
  },
];

export const feedItems: FeedItem[] = [
  {
    id: "post-1",
    boardId: "all",
    author: "김보현",
    role: "대표이사",
    title: "4월 말 전사 이슈 취합",
    body: "각 팀은 오늘 중으로 진행 중인 이슈와 병목을 댓글로 남겨주세요. 물류 지연 예상 일정, 거래처 응대 건을 우선 확인합니다.",
    status: "진행중",
    priority: "important",
    tags: ["#전사공지", "#이슈취합"],
    mentions: ["@콘텐츠팀", "@물류팀", "@영업팀"],
    attachments: 1,
    comments: 12,
    updatedAt: "10분 전",
    pinned: true,
  },
  {
    id: "post-2",
    boardId: "logistics",
    author: "이서준",
    role: "물류팀",
    title: "B2B 출고 지연 건 공유",
    body: "택배사 물량 증가로 일부 출고가 하루 밀렸습니다. 영업팀은 예상 도착일을 정리해서 공유해 주시고, 고객별 응대 문구가 필요합니다.",
    status: "보류",
    priority: "important",
    tags: ["#물류지연", "#고객응대"],
    mentions: ["@영업팀"],
    attachments: 2,
    comments: 5,
    updatedAt: "32분 전",
    pinned: true,
  },
  {
    id: "post-3",
    boardId: "weekly",
    author: "박지민",
    role: "콘텐츠팀",
    title: "2026-04 4주차 업무 기록",
    body: "이번 주 목표는 상세페이지 3종 완성입니다. 진행 업무 2건은 완료했고, 촬영 리소스 1건이 다음 주로 이월되었습니다.",
    status: "공유",
    priority: "normal",
    tags: ["#주간업무", "#상세페이지"],
    mentions: ["@대표"],
    attachments: 0,
    comments: 3,
    updatedAt: "1시간 전",
  },
  {
    id: "post-4",
    boardId: "sales",
    author: "최유나",
    role: "영업팀",
    title: "신규 거래처 샘플 발송 요청",
    body: "A거래처에서 샘플 20개를 요청했습니다. 생산팀 재고 확인 후 물류팀 출고 가능 시간 회신 부탁드립니다.",
    status: "진행중",
    priority: "normal",
    tags: ["#신규거래처", "#샘플"],
    mentions: ["@생산팀", "@물류팀"],
    attachments: 1,
    comments: 7,
    updatedAt: "2시간 전",
  },
  {
    id: "post-5",
    boardId: "all",
    author: "문소연",
    role: "경영관리실",
    title: "긴 본문과 많은 댓글 테스트",
    body: "실제 업무에서는 하나의 이슈가 여러 팀을 거치며 길어질 수 있습니다.\n\n물류팀은 출고 가능 시간과 재고 현황을 공유해야 하고, 영업팀은 고객 안내 문구와 우선순위를 정리해야 합니다. 콘텐츠팀은 공지 문구와 상세페이지 수정 여부를 확인하며, 경영관리실은 비용 또는 정산 영향이 있는지 별도로 검토합니다.\n\n본문이 길어져도 댓글 팝업 상단의 원문 영역은 일정 높이 안에서 확인 가능해야 하고, 댓글 목록은 별도로 스크롤되어야 합니다.",
    status: "공유",
    priority: "normal",
    tags: ["#테스트", "#긴본문", "#댓글많음"],
    mentions: ["@물류팀", "@영업팀", "@콘텐츠팀", "@경영관리실"],
    attachments: 1,
    comments: 16,
    updatedAt: "방금 전",
    pinned: true,
  },
];

export const comments: ThreadComment[] = [
  {
    id: "comment-1",
    author: "이서준",
    body: "물류팀 이슈는 오늘 16시까지 고객별 영향도를 표로 정리하겠습니다.",
    createdAt: "8분 전",
    replies: [
      {
        id: "comment-1-1",
        author: "최유나",
        body: "영업팀에서 고객 안내 문구 초안까지 같이 붙이겠습니다.",
        createdAt: "5분 전",
      },
    ],
  },
  {
    id: "comment-2",
    author: "박지민",
    body: "상세페이지 일정은 촬영본 수급 후 다시 업데이트하겠습니다.",
    createdAt: "3분 전",
  },
  {
    id: "comment-3",
    author: "강태오",
    body: "신사업 쪽 제휴 고객에게도 동일 안내가 필요한지 확인하겠습니다.",
    createdAt: "2분 전",
  },
  {
    id: "comment-4",
    author: "김보현",
    body: "각 팀 의견을 취합해서 오늘 마감 전 최종 대응안을 확정합시다.",
    createdAt: "방금 전",
  },
];

export const attachments: Attachment[] = [
  {
    id: "file-1",
    postId: "post-1",
    fileName: "전사_이슈_취합표.xlsx",
    fileType: "XLSX",
    fileSize: "84 KB",
    uploadedBy: "김보현",
    uploadedAt: "10분 전",
  },
  {
    id: "file-2",
    postId: "post-2",
    fileName: "B2B_출고지연_고객별현황.pdf",
    fileType: "PDF",
    fileSize: "212 KB",
    uploadedBy: "이서준",
    uploadedAt: "31분 전",
  },
  {
    id: "file-3",
    postId: "post-2",
    fileName: "고객안내_문구초안.docx",
    fileType: "DOCX",
    fileSize: "42 KB",
    uploadedBy: "최유나",
    uploadedAt: "24분 전",
  },
  {
    id: "file-4",
    postId: "post-5",
    fileName: "댓글팝업_테스트_체크리스트.xlsx",
    fileType: "XLSX",
    fileSize: "128 KB",
    uploadedBy: "문소연",
    uploadedAt: "방금 전",
  },
];

export const notifications: Notification[] = [
  {
    id: "noti-1",
    title: "@물류팀 멘션",
    source: "B2B 출고 지연 건 공유",
    read: false,
    important: true,
  },
  {
    id: "noti-2",
    title: "댓글 3개 등록",
    source: "4월 말 전사 이슈 취합",
    read: false,
  },
  {
    id: "noti-3",
    title: "주간 업무 등록",
    source: "콘텐츠팀 2026-04 4주차",
    read: true,
  },
];

export const quickStats = [
  { label: "진행중", value: "14", icon: ClipboardList },
  { label: "중요", value: "5", icon: Bell },
  { label: "첨부", value: "9", icon: Package },
  { label: "참여자", value: "32", icon: Users },
];

export const participants: Participant[] = [
  { id: "user-1", name: "김보현", department: "대표이사", role: "총괄 관리자" },
  { id: "user-2", name: "박지민", department: "콘텐츠팀", role: "상세페이지" },
  { id: "user-3", name: "정하은", department: "콘텐츠팀", role: "촬영/편집" },
  { id: "user-4", name: "최유나", department: "영업팀", role: "B2B 영업" },
  { id: "user-5", name: "오민재", department: "영업팀", role: "거래처 관리" },
  { id: "user-6", name: "서도윤", department: "생산팀", role: "생산 일정" },
  { id: "user-7", name: "이서준", department: "물류팀", role: "출고/배송" },
  { id: "user-8", name: "한서연", department: "물류팀", role: "재고 관리" },
  { id: "user-9", name: "강태오", department: "신사업팀", role: "시장 조사" },
  { id: "user-10", name: "문소연", department: "경영관리실", role: "정산/인사" },
];
